App\Entity\User:
    properties:
        email:
            -   NotBlank: ~
            -   Length:
                    min: 6
                    max: 150
        name:
            -   NotBlank: ~
            -   Length:
                    min: 6
                    max: 150
        password:
            -   NotBlank: ~
            -   Length:
                    min: 5
